version: '3'
services:
  api:
    container_name: django_rest_api
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    container_name: mysql816
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'example-api'
      MYSQL_USER: 'devuser'
      MYSQL_PASSWORD: 'devpass'
      MYSQL_ROOT_PASSWORD: 'devpass'
    ports:
      - 6032:3306